swagger: "2.0"
info:
  version: "0.0.1"
  title: oauth wrapped hw2
# during dev, should point to your local machine
host: localhost
# basePath prefixes all resource paths
basePath: /
#
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
  - application/x-www-form-urlencoded
# format of the responses to the client (Accepts)
produces:
  - application/json
x-a127-config:
  HW3.key: &apigeeProxyKey CONFIGURED
  HW3.uri: &apigeeProxyUri CONFIGURED
x-a127-services:
  oauth2:
      provider: volos-oauth-apigee
      options:
        tokenLifetime: 300000
        key: *apigeeProxyKey
        uri: *apigeeProxyUri
        #cache: mycache (See Oauth options section below.)
        validGrantTypes:
          - client_credentials
          - authorization_code
          - implicit_grant
          - password
        tokenPaths:  # These will be added to your paths section for you
          authorize: /authorize
          token: /accesstoken
          invalidate: /invalidate
          refresh: /refresh
paths:
  /oauth:
    # binds a127 app logic to a route
    x-swagger-router-controller: ncranonHW3
    x-a127-apply: {}
    get:
      description: Returns the request header information and if authorization is successful, information about github user 'pksunkara'
      # used as the method name of the controller
      operationId: qryStr
      security:
      - oauth2: []
      responses:
        "200":
          description: Success
          schema:
            # a pointer to a definition
            $ref: "#/definitions/HelloWorldResponse"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  HelloWorldResponse:
    required:
      - message
    properties:
      message:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
securityDefinitions:
  oauth2:
    type: oauth2
    scopes:
      read: "allow read"
    flow: application
    tokenUrl: ignored
